[build]
builder = "nixpacks"

[deploy]
startCommand = "python wsgi.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "checkers-api"
startCommand = "python wsgi.py"
healthCheckPath = "/health"
healthCheckTimeoutSeconds = 30