[build]
builder = "nixpacks"

[deploy]
startCommand = "python api_v2.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "checkers-api"
startCommand = "python api_v2.py"